version: "3.1"
services:

  redis:
    image: redis:alpine
    container_name: hangman-redis

  webserver:
    image: nginx:alpine
    container_name: hangman-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4201:80"

  php-fpm:
    build: docker/php-fpm
    container_name: hangman-php-fpm
    working_dir: /application
    volumes:
      - .:/application
